<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        const simplePromiseBuilder2 = value => {
                return new Promise((resolve, reject) => {
                        if (value) {
                            resolve(value)
                        } else {
                            reject(value)
                        }
                    })
                    .then(res => {
                        console.log(res)
                    })
                    .catch(err => {
                        console.error(err)
                    })
            }
            //   simplePromiseBuilder2(1)
            //  simplePromiseBuilder2()

        const prom = new Promise((resolve, reject) => {
            resolve()
            reject()
            console.log('Promise')
        })
        prom.then(() => {
            console.log('then')
        })
        prom.catch(() => {
            console.log('catch')
        })
        console.log('curious')

        new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve('first promise')
                }, 1000)
            })
            .then(res => {
                console.log(res)
                    //다음 덴의 리졸ㄹ브로 들어가느느 아이를 리턴
                return 'second promist'
            })
            .then(res => {
                console.log(res)
                return new Promise((resolve, reject) => {
                    //새로운 인스턴스 만들었쪄요
                    //리턴값 없음 언디파인으로 보통 가요
                    setTimeout(() => {
                        resolve('third promise')
                    }, 1000)
                })
            })
            .then(res => {
                console.log(res)
            })
            .catch(err => {
                console.error(err)
                return new Error('this error catched then')
            })
            .then(res => {
                console.log(res)
                throw new Error('this error catched catch')
            })
            .then(res => {
                console.error(err)
            })

        new Promise((res, rej) => {
                throw new Error('error')
                return 1;
            }).then(res => {
                consolel.log(res)
            })
            .cotch(err => {
                console.log(err)
            })
    </script>
</body>

</html>